### ISSUE TITLE
Mod is still not working on servers, causing them to crash

### ISSUE THREAD

**Issue by KondiU** [camcamcamcamcam/mindful-eating#6]
Today I wanted to try the newest version of this mod on my server but It seems that the crashing issue is still not fixed based on my log.

`[27Dec2021 18:21:25.880] [main/FATAL] [net.minecraft.server.Main/]: Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
	Mindful Eating (mindful_eating) has failed to load correctly
§7java.lang.NoClassDefFoundError: com/mojang/blaze3d/matrix/MatrixStack
]
	at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:269) ~[forge:?]
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:236) ~[forge:?]
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:194) ~[forge:?]
	at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:44) ~[forge:?]
	at net.minecraft.server.Main.main(Main.java:95) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge-1.16.5-36.2.4.jar:36.2]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHand/home/mcserver/Desktop/guacamole_dropler.java:54) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?]
	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge-1.16.5-36.2.4.jar:?]
	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge-1.16.5-36.2.4.jar:?]
	at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge-1.16.5-36.2.4.jar:?]`

**Comment by Nyancatpig** [comment]
I'm having this issue also

**Comment by camcamcamcamcam** [comment]
Alright sorry it took a while but I've released a new 1.16.5 version which fixes this hopefully
